[package]
name = "diwag"
version = "0.1.0"
authors = ["Jhon James Quintero <jojaquix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lang-c = "0.9.0"
